### ISSUE TITLE
Use two 32-bit or one 64-bit integer instead of two 16-bit ones

### ISSUE THREAD

**Issue by batyrmastyr** [yiisoft/mutex-pdo-pgsql#17]
Currently package transforms mutex name to [two unsigned 16-bit integers](https://github.com/yiisoft/mutex-pdo-pgsql/blob/master/src/PgsqlMutex.php#L29-L30): `$this->lockKeys = array_values(unpack('n2', sha1($name, true)));` 
PostgreSQL accepts two 32-bit signed integers or one 64-bit signed integer, so It's possible to lower the risk of collisions.

| Q                | A
| ---------------- | ---
| Version          | 1.0
| PHP version      | any
| Operating system | any

**Comment by devanych** [comment]
In this case, there is no difference, since `sha1()` generates a constant hash from the specified mutex name.

A 16-bit or 32-bit or 64-bit integer will always be the same based on the name of the mutex.

Therefore, this will not affect the risk of collisions in any way. With the current approach, everything will work without collisions.

**Comment by batyrmastyr** [comment]
The hash is the same but current code uses only first 4 bytes of it. 
Well, it’s not so big deal to wait until some other unrelated mutex with same hash prefix is released, but it’s better to lower such probability.

**Comment by devanych** [comment]
You would be right if the probability was different. But it is not different, so it makes no sense. We will simply change 16-bit to 32-bit, but the essence will not change.

**Comment by samdark** [comment]
Thanks for keeping an eye on the code, @batyrmastyr. Checked it. Looks alright as is.

**Comment by batyrmastyr** [comment]
> But it is not different
So you say that the result of `substr(sha1('some text', true), 0, N) === substr(sha1('another text', true), 0, N)` is the same no matter what N you take: 1, 2, 4, 8, 16 or 20? And this works with any input strings? I want to know how did you calculate this.

**Comment by samdark** [comment]
Two 32 bit singned ints contain the same amount of bytes as one 64 bit int.

**Comment by batyrmastyr** [comment]
@samdark current code uses two **16** bit ints, so 16 + 16 < 32 + 32.

**Comment by samdark** [comment]
Ah. Right. Yes, could likely be improved.

**Comment by samdark** [comment]
Re-checked. Collision probability right now is 2^-16 * 2^-16 that is more than acceptable for user-defined input values. There won't be many. Thousands at max.
